# Author: Aniruddha Gokhale
# Vanderbilt University
# Created May 2017,
# Modified Nov 2017
# Modified Oct 2018
# Modified Oct 2019 to use Python3
# Modified Spring 2021 to break this into client-server
#
# For Cloud Computing class
#
# First, use the latest ubuntu image, which points to the
# latest LTS image, currently 20.04LTS
FROM ubuntu:latest
ENV TZ=US/NewYork
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update && apt-get install -y tzdata
RUN apt-get -y update && apt-get install -y curl
# RUN apt-get -y update && apt-get install -y net-tools python3 gcc python3-dev python3-pip curl default-jdk


ARG kafka_version=2.7.0
ARG scala_version=2.13
ARG glibc_version=2.27-r0

ENV KAFKA_VERSION=$kafka_version \
    SCALA_VERSION=$scala_version \
    KAFKA_HOME=/opt/kafka \
    GLIBC_VERSION=$glibc_version

ENV PATH=${PATH}:${KAFKA_HOME}/bin
RUN mkdir -p /opt/kafka
Run echo "https://downloads.apache.org/kafka/${KAFKA_VERSION}/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -o /opt/kafka/kafka.tgz"
RUN curl https://downloads.apache.org/kafka/https://downloads.apache.org/kafka/2.7.0/kafka_2.13-2.7.0.tgz -o /opt/kafka/kafka.tgz
Run ls -l /opt/kafka/kafka.tgz
RUN tar xvf /opt/kafka/kafka.tgz  -C /opt/kafka
